import Birthday1 from './assets/images/download.jpeg';
import romantic from './assets/images/romantic.jpeg'
import ring from './assets/images/ring.jpeg'
import ceiling from './assets/images/ceiling.jpeg'
import adult from './assets/images/18th.jpeg'
import mini from './assets/images/minimal.jpeg'
import jungle from './assets/images/wp1.png'
import thirty from './assets/images/30th Happy Birthday Decorations.jpeg'

const products = [
  // ===== BIRTHDAY DECORATIONS (25 products) =====
  { 
    id: 1, 
    name: "Colorful & Beautiful Balloon Ring", 
    category: "birthday", 
    subCategory: "25th Birthday", 
    price: 2800, 
    originalPrice: 3500, 
    image: ring, 
    description: "Stunning rainbow balloon arch perfect for birthdays", 
    fullDescription: "Transform your 25th birthday celebration into a vibrant and unforgettable experience with our stunning rainbow balloon arch. This eye-catching decoration piece serves as the perfect backdrop for your special day.", 
    features: ["Premium quality latex balloons in multiple vibrant colors", "Professionally designed arch structure spanning 8-10 feet", "Customizable color scheme to match your party theme", "Includes installation and removal service", "Perfect for photo opportunities and social media moments", "Durable design that lasts throughout the event"], 
    includes: "Balloon arch setup, color consultation, on-site installation team, and cleanup service", 
    setupTime: "2-3 hours", 
    rating: 4.5, 
    ratingCount: 45, 
    discount: 20 
  },
  { 
    id: 4, 
    name: "Ceiling Balloons Setup", 
    category: "birthday", 
    subCategory: "1st Birthday", 
    price: 2200, 
    originalPrice: 2800, 
    image: ceiling, 
    description: "Beautiful floating ceiling balloon arrangement", 
    fullDescription: "Create a magical wonderland for your little one's first birthday with our enchanting ceiling balloon setup.", 
    features: ["Safe, non-toxic helium-filled balloons", "Age-appropriate color schemes", "Ceiling coverage creating a canopy effect", "Mix of solid colors and themed prints", "Ground balloon clusters for added decoration", "Complimentary first birthday banner"], 
    includes: "Helium-filled balloons, ceiling attachment, themed accessories, and safety-compliant materials", 
    setupTime: "2 hours", 
    rating: 4.6, 
    ratingCount: 51, 
    discount: 21 
  },
  { 
    id: 6, 
    name: "Minimal & Elegant Birthday", 
    category: "birthday", 
    subCategory: "Birthday", 
    price: 1599, 
    originalPrice: 2000, 
    image: mini, 
    description: "Sophisticated minimalist birthday decoration", 
    fullDescription: "Celebrate your birthday with our sophisticated minimalist birthday decoration.", 
    features: ["Clean, modern aesthetic design", "Elegant color palette selection", "Premium quality minimal decorations", "Strategic placement for maximum impact", "Sophisticated balloon arrangements", "Classy table centerpieces"], 
    includes: "Curated minimal decor elements, color-coordinated setup, and elegant finishing touches", 
    setupTime: "2 hours", 
    rating: 4.4, 
    ratingCount: 33, 
    discount: 20 
  },
  {
    id: 101,
    name: "Grand 60th Birthday Celebration",
    category: "birthday",
    subCategory: "60th Birthday",
    price: 4200,
    originalPrice: 5000,
    image: Birthday1,
    description: "Luxurious golden themed 60th birthday decoration",
    fullDescription: "Celebrate six decades of life with our grand 60th birthday decoration package featuring elegant golden accents.",
    features: ["Luxurious blue theme throughout", "Premium quality balloons and draping", "Milestone number display", "Elegant table settings", "Photo booth with props", "Personalized birthday banner"],
    includes: "Complete venue decoration, golden theme elements, photo props, and milestone displays",
    setupTime: "4 hours",
    rating: 4.9,
    ratingCount: 28,
    discount: 16
  },
  {
    id: 102,
    name: "Jungle Theme decor setup",
    category: "birthday",
    subCategory: "1st Birthday",
    price: 3100,
    originalPrice: 3800,
    image: jungle,
    description: "Action-packed superhero themed birthday party",
    fullDescription: "Step into the wild with our Jungle Theme Balloon Décor! 🦁🌿 This playful setup includes a vibrant mix of green, brown, and yellow balloons styled with a backdrop and banner, along with adorable animal foil balloons that bring the jungle to life. Perfect for kids’ birthdays and themed parties, this décor creates a fun and lively atmosphere where little ones can feel like they’re on a safari adventure. At just ₹2700, it’s an eye-catching yet budget-friendly setup that doubles as the perfect photo backdrop for unforgettable memories.",
    features: ["Adds a fun and lively atmosphere to your event.", "Customizable to suit any theme or occasion.", "Long-lasting and reusable with proper care."],
    includes: "350 jungle themed color balloons, Age balloon + Animaal foils for elegant touch up 4, Back banner with kid's image",
    setupTime: "3 hours",
    rating: 4.7,
    ratingCount: 42,
    discount: 18
  },
  {
    id: 103,
    name: "Sweet 18 Modern Elegance",
    category: "birthday",
    subCategory: "18th Birthday",
    price: 3500,
    originalPrice: 4200,
    image: adult,
    description: "Chic and modern 18th birthday decoration",
    fullDescription: "Mark the transition to adulthood with our sophisticated 18th birthday decoration package.",
    features: ["Modern geometric designs", "Metallic gold and rose gold accents", "LED string lights", "Instagram-worthy photo corners", "Number 18 display piece", "Elegant table centerpieces"],
    includes: "Modern decor elements, lighting setup, photo backdrop, and themed accessories",
    setupTime: "3 hours",
    rating: 4.8,
    ratingCount: 56,
    discount: 17
  },
  {
    id: 108,
    name: "Elegant 30th Birthday Setup",
    category: "birthday",
    subCategory: "30th Birthday",
    price: 3600,
    originalPrice: 4300,
    image: thirty,
    description: "Sophisticated 30th birthday celebration decor",
    fullDescription: "Welcome a new decade with our elegant and refined 30th birthday decoration package.",
    features: ["Rose gold and black theme", "Premium balloon garlands", "Floral arrangements", "Number 30 installation", "Elegant draping", "Sophisticated table settings"],
    includes: "Complete elegant setup, floral elements, premium balloons, Happy Birthday banner and refined decorations",
    setupTime: "3-4 hours",
    rating: 4.9,
    ratingCount: 48,
    discount: 16
  },
  {
    id: 109,
    name: "Red Theme Romantic Birthday decor",
    category: "birthday",
    subCategory: "28th Birthday",
    price: 2500,
    originalPrice: 3300,
    image: romantic,
    description: "Out-of-this-world space themed birthday",
    fullDescription: "Launch into an intergalactic celebration with our space explorer birthday theme.",
    features: ["Neon light with Backdrop banner", "Premium quality decorative elements",  "Table centerpieces and backdrop setup", "Coordinated theme throughout the venue", "Red and Pink coloured heart shaped balloons", "Premium Balloon Styling"], 
    includes: "Romantic theme setup, glow decorations, and themed accessories",
    setupTime: "3 hours",
    rating: 4.6,
    ratingCount: 31,
    discount: 18
  },

  // ===== BABY SHOWER DECORATIONS =====
  { 
    id: 2, 
    name: "It's a Boy Beautiful & Minimal", 
    category: "baby-shower", 
    subCategory: "Boy Baby Shower", 
    price: 1800, 
    originalPrice: 2200, 
    image: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=500", 
    description: "Elegant blue themed baby shower decoration", 
    fullDescription: "Celebrate the upcoming arrival of your baby boy with our elegant and minimal baby shower decoration package. Featuring soothing blue tones and sophisticated design elements that create the perfect atmosphere for this special occasion.", 
    features: ["Elegant blue and white color palette", "Premium quality decorative elements", "Personalized welcome signage", "Table centerpieces and backdrop setup", "Photo booth area with props", "Coordinated theme throughout the venue"], 
    includes: "Complete venue decoration, backdrop, table settings, welcome board, and themed accessories", 
    setupTime: "3-4 hours", 
    rating: 4.8, 
    ratingCount: 62, 
    discount: 18 
  },
  { 
    id: 7, 
    name: "Baby Shower Balloon Décor", 
    category: "baby-shower", 
    subCategory: "Girl Baby Shower", 
    price: 1750, 
    originalPrice: 2100, 
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500", 
    description: "Pastel colored baby shower balloon setup", 
    fullDescription: "Welcome your baby girl with our beautiful pastel-themed baby shower decoration.", 
    features: ["Soft pastel color palette", "Premium balloon garland installation", "Gender-specific themed elements", "Cute and adorable props", "Instagram-worthy photo corners", "Coordinated table decorations"], 
    includes: "Balloon arrangements, themed props, welcome signage, and complete color coordination", 
    setupTime: "2-3 hours", 
    rating: 4.8, 
    ratingCount: 56, 
    discount: 17 
  },
  { 
    id: 8, 
    name: "Baby Shower Ring Setup", 
    category: "baby-shower", 
    subCategory: "Twin Baby Shower", 
    price: 4200, 
    originalPrice: 5000, 
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=500", 
    description: "Premium circular baby shower decoration", 
    fullDescription: "Double the joy with our premium twin baby shower decoration package.", 
    features: ["Unique circular/ring design setup", "Dual-theme elements for twins", "Premium quality materials throughout", "360-degree decorated centerpiece", "Matching pair decorative elements", "Special twin-themed accessories"], 
    includes: "Circular structure setup, dual theme coordination, premium materials, and specialized twin-themed decor", 
    setupTime: "4 hours", 
    rating: 4.9, 
    ratingCount: 41, 
    discount: 16 
  },
  { 
    id: 9, 
    name: "Baby Shower Ring Setup Premium", 
    category: "baby-shower", 
    subCategory: "Gender Reveal", 
    price: 2300, 
    originalPrice: 2800, 
    image: "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=500", 
    description: "Yellow themed baby shower decoration ring", 
    fullDescription: "Keep everyone guessing with our exciting gender reveal party decoration.", 
    features: ["Gender-neutral yellow theme", "Question mark and surprise elements", "Reveal-ready balloon arrangements", "Photo-worthy reveal backdrop", "Anticipation-building decorations", "Includes reveal props and accessories"], 
    includes: "Complete gender reveal setup, neutral theme decor, reveal props, and photo backdrop", 
    setupTime: "3 hours", 
    rating: 4.7, 
    ratingCount: 44, 
    discount: 18 
  },

  // ===== ANNIVERSARY DECORATIONS =====
  { 
    id: 3, 
    name: "Golden 25th Anniversary Special", 
    category: "anniversary", 
    subCategory: "25th Anniversary", 
    price: 4699, 
    originalPrice: 5500, 
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=500", 
    description: "Luxurious golden themed anniversary decoration", 
    fullDescription: "Mark your 25 years of love and togetherness with our luxurious golden anniversary decoration package. This elegant setup celebrates your silver jubilee with sophistication and grandeur.", 
    features: ["Luxurious golden and ivory color scheme", "Premium metallic balloons and draping", "Elegant table settings with golden accents", "Romantic lighting arrangements", "Personalized anniversary milestone display", "Professional photography backdrop"], 
    includes: "Complete venue transformation, lighting setup, floral arrangements, personalized elements, and professional styling", 
    setupTime: "4-5 hours", 
    rating: 4.9, 
    ratingCount: 38, 
    discount: 15 
  },

  // ===== THEME DECORATIONS =====
  { 
    id: 5, 
    name: "Jungle Theme Décor Setup", 
    category: "theme", 
    subCategory: "Jungle Theme", 
    price: 2700, 
    originalPrice: 3200, 
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500", 
    description: "Wild and adventurous jungle themed decoration", 
    fullDescription: "Take your guests on a wild adventure through the jungle with our immersive themed decoration package.", 
    features: ["Life-sized animal cutouts and props", "Lush green foliage and tropical elements", "Safari-themed backdrop for photos", "Jungle-inspired table settings", "Themed entrance archway", "Animal print balloons and banners"], 
    includes: "Complete theme transformation, props, signage, tableware suggestions, and immersive decorative elements", 
    setupTime: "3-4 hours", 
    rating: 4.7, 
    ratingCount: 29, 
    discount: 16 
  },
  { 
    id: 10, 
    name: "Extravagant Beautiful Balloons", 
    category: "theme", 
    subCategory: "Princess Theme", 
    price: 3700, 
    originalPrice: 4500, 
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=500", 
    description: "Luxurious multi-color balloon decoration", 
    fullDescription: "Make your little princess feel like royalty with our extravagant princess-themed decoration package.", 
    features: ["Royal princess theme throughout", "Castle and crown decorative elements", "Luxurious balloon arrangements", "Pink and gold color scheme", "Throne photo op area", "Princess-themed props and accessories"], 
    includes: "Complete princess theme transformation, castle backdrop, crown elements, and royal-themed accessories", 
    setupTime: "4 hours", 
    rating: 4.6, 
    ratingCount: 37, 
    discount: 18 
  },
  { 
    id: 11, 
    name: "Superhero Adventure Theme", 
    category: "theme", 
    subCategory: "Superhero Theme", 
    price: 3200, 
    originalPrice: 3800, 
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=500", 
    description: "Action-packed superhero themed decoration", 
    fullDescription: "Transform your venue into a superhero headquarters with our action-packed themed decoration.", 
    features: ["Popular superhero characters and logos", "City skyline backdrop", "Bold primary color scheme", "Action pose photo opportunities", "Comic book style decorative elements", "Hero mask party favors"], 
    includes: "Superhero themed backdrop, character cutouts, themed balloons, and action-packed decorative elements", 
    setupTime: "3-4 hours", 
    rating: 4.8, 
    ratingCount: 52, 
    discount: 16 
  }
];

export default products;