import Birthday1 from './assets/images/download.jpeg'

const products = [
  // ===== BIRTHDAY DECORATIONS (25 products) =====
  { 
    id: 1, 
    name: "Colorful & Beautiful Balloon Arch", 
    category: "birthday", 
    subCategory: "25th Birthday", 
    price: 2800, 
    originalPrice: 3500, 
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=500", 
    description: "Stunning rainbow balloon arch perfect for birthdays", 
    fullDescription: "Transform your 25th birthday celebration into a vibrant and unforgettable experience with our stunning rainbow balloon arch. This eye-catching decoration piece serves as the perfect backdrop for your special day.", 
    features: ["Premium quality latex balloons in multiple vibrant colors", "Professionally designed arch structure spanning 8-10 feet", "Customizable color scheme to match your party theme", "Includes installation and removal service", "Perfect for photo opportunities and social media moments", "Durable design that lasts throughout the event"], 
    includes: "Balloon arch setup, color consultation, on-site installation team, and cleanup service", 
    setupTime: "2-3 hours", 
    rating: 4.5, 
    ratingCount: 45, 
    discount: 20 
  },
  { 
    id: 4, 
    name: "Ceiling Balloons Setup", 
    category: "birthday", 
    subCategory: "1st Birthday", 
    price: 2200, 
    originalPrice: 2800, 
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=500", 
    description: "Beautiful floating ceiling balloon arrangement", 
    fullDescription: "Create a magical wonderland for your little one's first birthday with our enchanting ceiling balloon setup.", 
    features: ["Safe, non-toxic helium-filled balloons", "Age-appropriate color schemes", "Ceiling coverage creating a canopy effect", "Mix of solid colors and themed prints", "Ground balloon clusters for added decoration", "Complimentary first birthday banner"], 
    includes: "Helium-filled balloons, ceiling attachment, themed accessories, and safety-compliant materials", 
    setupTime: "2 hours", 
    rating: 4.6, 
    ratingCount: 51, 
    discount: 21 
  },
  { 
    id: 6, 
    name: "Minimal & Elegant Birthday", 
    category: "birthday", 
    subCategory: "50th Birthday", 
    price: 1599, 
    originalPrice: 2000, 
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=500", 
    description: "Sophisticated minimalist birthday decoration", 
    fullDescription: "Celebrate 50 years of wonderful memories with our sophisticated minimalist birthday decoration.", 
    features: ["Clean, modern aesthetic design", "Elegant color palette selection", "Premium quality minimal decorations", "Strategic placement for maximum impact", "Sophisticated balloon arrangements", "Classy table centerpieces"], 
    includes: "Curated minimal decor elements, color-coordinated setup, and elegant finishing touches", 
    setupTime: "2 hours", 
    rating: 4.4, 
    ratingCount: 33, 
    discount: 20 
  },
  {
    id: 101,
    name: "Grand 60th Birthday Celebration",
    category: "birthday",
    subCategory: "60th Birthday",
    price: 4200,
    originalPrice: 5000,
    image: Birthday1,
    description: "Luxurious golden themed 60th birthday decoration",
    fullDescription: "Celebrate six decades of life with our grand 60th birthday decoration package featuring elegant golden accents.",
    features: ["Luxurious blue theme throughout", "Premium quality balloons and draping", "Milestone number display", "Elegant table settings", "Photo booth with props", "Personalized birthday banner"],
    includes: "Complete venue decoration, golden theme elements, photo props, and milestone displays",
    setupTime: "4 hours",
    rating: 4.9,
    ratingCount: 28,
    discount: 16
  },
  {
    id: 102,
    name: "Superhero 10th Birthday Bash",
    category: "birthday",
    subCategory: "10th Birthday",
    price: 3100,
    originalPrice: 3800,
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=500",
    description: "Action-packed superhero themed birthday party",
    fullDescription: "Transform your venue into a superhero headquarters for an unforgettable 10th birthday celebration.",
    features: ["Popular superhero characters", "City skyline backdrop", "Bold primary colors", "Action pose photo spots", "Comic book elements", "Hero masks for guests"],
    includes: "Superhero backdrop, character cutouts, themed balloons, and party accessories",
    setupTime: "3 hours",
    rating: 4.7,
    ratingCount: 42,
    discount: 18
  },
  {
    id: 103,
    name: "Sweet 18 Modern Elegance",
    category: "birthday",
    subCategory: "18th Birthday",
    price: 3500,
    originalPrice: 4200,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=500",
    description: "Chic and modern 18th birthday decoration",
    fullDescription: "Mark the transition to adulthood with our sophisticated 18th birthday decoration package.",
    features: ["Modern geometric designs", "Metallic gold and rose gold accents", "LED string lights", "Instagram-worthy photo corners", "Number 18 display piece", "Elegant table centerpieces"],
    includes: "Modern decor elements, lighting setup, photo backdrop, and themed accessories",
    setupTime: "3 hours",
    rating: 4.8,
    ratingCount: 56,
    discount: 17
  },
  {
    id: 104,
    name: "Princess Fairy 5th Birthday",
    category: "birthday",
    subCategory: "5th Birthday",
    price: 2900,
    originalPrice: 3500,
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=500",
    description: "Magical princess themed birthday decoration",
    fullDescription: "Create a fairy tale experience for your little princess's 5th birthday celebration.",
    features: ["Pink and purple princess theme", "Castle backdrop elements", "Crown and tiara decorations", "Fairy lights and tulle draping", "Princess character cutouts", "Royal throne photo spot"],
    includes: "Princess theme setup, castle elements, fairy lights, and royal accessories",
    setupTime: "3 hours",
    rating: 4.6,
    ratingCount: 38,
    discount: 17
  },
  {
    id: 105,
    name: "Fabulous 40th Birthday Party",
    category: "birthday",
    subCategory: "40th Birthday",
    price: 3800,
    originalPrice: 4500,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=500",
    description: "Elegant and sophisticated 40th birthday setup",
    fullDescription: "Celebrate four fabulous decades with our premium 40th birthday decoration package.",
    features: ["Elegant black and gold theme", "Premium balloon arrangements", "Milestone photo display", "Sophisticated lighting", "Champagne bar setup area", "Personalized 40th elements"],
    includes: "Complete elegant setup, lighting, photo displays, and premium decorations",
    setupTime: "4 hours",
    rating: 4.7,
    ratingCount: 44,
    discount: 16
  },
  {
    id: 106,
    name: "Fun 21st Birthday Celebration",
    category: "birthday",
    subCategory: "21st Birthday",
    price: 3200,
    originalPrice: 3900,
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=500",
    description: "Vibrant and trendy 21st birthday decoration",
    fullDescription: "Ring in the milestone 21st birthday with our trendy and vibrant decoration package.",
    features: ["Trendy neon color scheme", "LED neon signs", "Modern balloon installations", "Photo booth with fun props", "Number 21 marquee lights", "Confetti and streamer accents"],
    includes: "Neon theme setup, LED elements, modern balloons, and party props",
    setupTime: "3 hours",
    rating: 4.8,
    ratingCount: 52,
    discount: 18
  },
  {
    id: 107,
    name: "Dinosaur Adventure 3rd Birthday",
    category: "birthday",
    subCategory: "3rd Birthday",
    price: 2400,
    originalPrice: 3000,
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=500",
    description: "Roaring dinosaur themed birthday party",
    fullDescription: "Take your little one on a prehistoric adventure with our exciting dinosaur birthday theme.",
    features: ["Colorful dinosaur cutouts", "Jungle foliage elements", "Volcano centerpiece", "Dino eggs decorations", "Prehistoric themed balloons", "Dinosaur footprint trails"],
    includes: "Dinosaur theme setup, jungle elements, themed balloons, and party accessories",
    setupTime: "2-3 hours",
    rating: 4.5,
    ratingCount: 36,
    discount: 20
  },
  {
    id: 108,
    name: "Elegant 30th Birthday Setup",
    category: "birthday",
    subCategory: "30th Birthday",
    price: 3600,
    originalPrice: 4300,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=500",
    description: "Sophisticated 30th birthday celebration decor",
    fullDescription: "Welcome a new decade with our elegant and refined 30th birthday decoration package.",
    features: ["Rose gold and white theme", "Premium balloon garlands", "Floral arrangements", "Number 30 installation", "Elegant draping", "Sophisticated table settings"],
    includes: "Complete elegant setup, floral elements, premium balloons, and refined decorations",
    setupTime: "3-4 hours",
    rating: 4.9,
    ratingCount: 48,
    discount: 16
  },
  {
    id: 109,
    name: "Space Explorer 7th Birthday",
    category: "birthday",
    subCategory: "7th Birthday",
    price: 2700,
    originalPrice: 3300,
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=500",
    description: "Out-of-this-world space themed birthday",
    fullDescription: "Launch into an intergalactic celebration with our space explorer birthday theme.",
    features: ["Planets and stars decorations", "Rocket ship centerpieces", "Galaxy backdrop", "Astronaut cutouts", "Glow-in-the-dark elements", "Space-themed balloons"],
    includes: "Space theme setup, cosmic elements, glow decorations, and themed accessories",
    setupTime: "3 hours",
    rating: 4.6,
    ratingCount: 31,
    discount: 18
  },
  {
    id: 110,
    name: "Unicorn Magic 6th Birthday",
    category: "birthday",
    subCategory: "6th Birthday",
    price: 2850,
    originalPrice: 3400,
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=500",
    description: "Magical unicorn themed birthday party",
    fullDescription: "Create a mystical unicorn wonderland for your child's magical 6th birthday.",
    features: ["Pastel rainbow colors", "Unicorn horn and ears props", "Cloud and rainbow decorations", "Magical fairy lights", "Unicorn balloon arrangements", "Glitter and shimmer accents"],
    includes: "Unicorn theme setup, rainbow elements, magical decorations, and party props",
    setupTime: "3 hours",
    rating: 4.7,
    ratingCount: 45,
    discount: 16
  },
  {
    id: 111,
    name: "Classic 70th Birthday Celebration",
    category: "birthday",
    subCategory: "70th Birthday",
    price: 4500,
    originalPrice: 5300,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=500",
    description: "Timeless and elegant 70th birthday decor",
    fullDescription: "Honor seven decades of life with our classic and elegant birthday decoration package.",
    features: ["Timeless color palette", "Memory photo displays", "Elegant floral arrangements", "Milestone number showcase", "Vintage-inspired elements", "Premium table settings"],
    includes: "Complete elegant setup, photo displays, premium florals, and classic decorations",
    setupTime: "4-5 hours",
    rating: 4.9,
    ratingCount: 22,
    discount: 15
  },
  {
    id: 112,
    name: "Safari Adventure 4th Birthday",
    category: "birthday",
    subCategory: "4th Birthday",
    price: 2600,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=500",
    description: "Wild safari themed birthday celebration",
    fullDescription: "Go on a wild safari adventure with our exciting animal-themed birthday decoration.",
    features: ["Safari animal cutouts", "Jungle foliage and vines", "Safari jeep photo prop", "Animal print balloons", "Binocular and hat props", "Safari themed table settings"],
    includes: "Safari theme setup, animal elements, jungle decorations, and themed accessories",
    setupTime: "3 hours",
    rating: 4.5,
    ratingCount: 34,
    discount: 19
  },
  {
    id: 113,
    name: "Gamer's Paradise 12th Birthday",
    category: "birthday",
    subCategory: "12th Birthday",
    price: 3300,
    originalPrice: 4000,
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=500",
    description: "Epic gaming themed birthday party",
    fullDescription: "Level up your birthday celebration with our ultimate gaming themed decoration package.",
    features: ["Video game inspired designs", "Controller and console props", "LED gaming lights", "Pixel art decorations", "Game character cutouts", "Arcade-style setup"],
    includes: "Gaming theme setup, LED lights, game props, and tech-inspired decorations",
    setupTime: "3 hours",
    rating: 4.8,
    ratingCount: 47,
    discount: 18
  },
  {
    id: 114,
    name: "Mermaid Under the Sea 8th Birthday",
    category: "birthday",
    subCategory: "8th Birthday",
    price: 2950,
    originalPrice: 3600,
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=500",
    description: "Enchanting underwater mermaid theme",
    fullDescription: "Dive into an underwater adventure with our magical mermaid birthday decoration.",
    features: ["Ocean blue and teal colors", "Mermaid tail decorations", "Sea creature props", "Bubble and wave elements", "Seashell and starfish accents", "Underwater backdrop"],
    includes: "Mermaid theme setup, ocean elements, sea decorations, and aquatic accessories",
    setupTime: "3 hours",
    rating: 4.6,
    ratingCount: 39,
    discount: 18
  },
  {
    id: 115,
    name: "Sports Champion 9th Birthday",
    category: "birthday",
    subCategory: "9th Birthday",
    price: 2800,
    originalPrice: 3400,
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=500",
    description: "All-star sports themed birthday party",
    fullDescription: "Score big with our action-packed sports themed birthday decoration package.",
    features: ["Multi-sport decorations", "Stadium-inspired setup", "Sports equipment props", "Team colors and pennants", "Trophy and medal displays", "Sports ball balloons"],
    includes: "Sports theme setup, equipment props, athletic decorations, and team accessories",
    setupTime: "3 hours",
    rating: 4.7,
    ratingCount: 41,
    discount: 17
  },
  {
    id: 116,
    name: "Woodland Forest 2nd Birthday",
    category: "birthday",
    subCategory: "2nd Birthday",
    price: 2300,
    originalPrice: 2900,
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=500",
    description: "Charming woodland creatures birthday theme",
    fullDescription: "Create a whimsical forest setting for your little one's 2nd birthday celebration.",
    features: ["Woodland animal cutouts", "Forest tree and leaf elements", "Moss and nature decorations", "Cute creature balloons", "Mushroom and acorn props", "Earthy color palette"],
    includes: "Woodland theme setup, animal elements, nature decorations, and forest accessories",
    setupTime: "2-3 hours",
    rating: 4.5,
    ratingCount: 29,
    discount: 21
  },
  {
    id: 117,
    name: "Rockstar 15th Birthday Bash",
    category: "birthday",
    subCategory: "15th Birthday",
    price: 3400,
    originalPrice: 4100,
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=500",
    description: "Cool rockstar themed teenage birthday",
    fullDescription: "Rock out with our edgy and cool rockstar birthday decoration package.",
    features: ["Music-inspired decorations", "Guitar and microphone props", "Stage lighting effects", "Rock band posters", "Vinyl record accents", "Concert-style setup"],
    includes: "Rockstar theme setup, music props, stage elements, and concert decorations",
    setupTime: "3 hours",
    rating: 4.6,
    ratingCount: 35,
    discount: 17
  },
  {
    id: 118,
    name: "Tropical Paradise 35th Birthday",
    category: "birthday",
    subCategory: "35th Birthday",
    price: 3700,
    originalPrice: 4400,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=500",
    description: "Vibrant tropical themed birthday celebration",
    fullDescription: "Escape to paradise with our vibrant tropical birthday decoration package.",
    features: ["Tropical leaf decorations", "Flamingo and pineapple props", "Bright vibrant colors", "Tiki bar setup area", "Exotic floral arrangements", "Beach-inspired elements"],
    includes: "Tropical theme setup, exotic elements, vibrant decorations, and island accessories",
    setupTime: "3-4 hours",
    rating: 4.8,
    ratingCount: 43,
    discount: 16
  },
  {
    id: 119,
    name: "Carnival Fun 11th Birthday",
    category: "birthday",
    subCategory: "11th Birthday",
    price: 3100,
    originalPrice: 3800,
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=500",
    description: "Exciting carnival themed birthday party",
    fullDescription: "Bring the carnival to your celebration with our fun-filled birthday decoration package.",
    features: ["Circus tent elements", "Carnival game props", "Popcorn and candy decorations", "Striped patterns", "Ferris wheel cutouts", "Festive bunting and flags"],
    includes: "Carnival theme setup, game props, festive decorations, and circus accessories",
    setupTime: "3 hours",
    rating: 4.7,
    ratingCount: 37,
    discount: 18
  },
  {
    id: 120,
    name: "Boho Chic 28th Birthday",
    category: "birthday",
    subCategory: "28th Birthday",
    price: 3500,
    originalPrice: 4200,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=500",
    description: "Stylish bohemian themed birthday decor",
    fullDescription: "Celebrate in style with our trendy boho chic birthday decoration package.",
    features: ["Macramé and tassel decorations", "Pampas grass arrangements", "Earthy neutral tones", "Dream catcher elements", "Vintage rugs and cushions", "Moroccan lanterns"],
    includes: "Boho theme setup, macramé elements, earthy decorations, and bohemian accessories",
    setupTime: "3-4 hours",
    rating: 4.8,
    ratingCount: 40,
    discount: 17
  },
  {
    id: 121,
    name: "Construction Site 4th Birthday",
    category: "birthday",
    subCategory: "4th Birthday",
    price: 2650,
    originalPrice: 3200,
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=500",
    description: "Fun construction themed birthday party",
    fullDescription: "Build memories with our exciting construction site birthday decoration package.",
    features: ["Construction vehicle cutouts", "Caution tape decorations", "Tool and gear props", "Hard hat party favors", "Orange and yellow theme", "Building block elements"],
    includes: "Construction theme setup, vehicle props, safety decorations, and building accessories",
    setupTime: "2-3 hours",
    rating: 4.6,
    ratingCount: 32,
    discount: 17
  },
  {
    id: 122,
    name: "Elegant 80th Birthday Gala",
    category: "birthday",
    subCategory: "80th Birthday",
    price: 4800,
    originalPrice: 5600,
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=500",
    description: "Prestigious 80th birthday celebration decor",
    fullDescription: "Honor eight magnificent decades with our prestigious birthday decoration package.",
    features: ["Luxurious gold and cream theme", "Elegant crystal accents", "Memory timeline displays", "Premium floral centerpieces", "Sophisticated lighting", "Classic table settings"],
    includes: "Luxury setup, memory displays, premium florals, and elegant decorations",
    setupTime: "4-5 hours",
    rating: 4.9,
    ratingCount: 18,
    discount: 14
  },

  // ===== BABY SHOWER DECORATIONS =====
  { 
    id: 2, 
    name: "It's a Boy Beautiful & Minimal", 
    category: "baby-shower", 
    subCategory: "Boy Baby Shower", 
    price: 1800, 
    originalPrice: 2200, 
    image: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=500", 
    description: "Elegant blue themed baby shower decoration", 
    fullDescription: "Celebrate the upcoming arrival of your baby boy with our elegant and minimal baby shower decoration package. Featuring soothing blue tones and sophisticated design elements that create the perfect atmosphere for this special occasion.", 
    features: ["Elegant blue and white color palette", "Premium quality decorative elements", "Personalized welcome signage", "Table centerpieces and backdrop setup", "Photo booth area with props", "Coordinated theme throughout the venue"], 
    includes: "Complete venue decoration, backdrop, table settings, welcome board, and themed accessories", 
    setupTime: "3-4 hours", 
    rating: 4.8, 
    ratingCount: 62, 
    discount: 18 
  },
  { 
    id: 7, 
    name: "Baby Shower Balloon Décor", 
    category: "baby-shower", 
    subCategory: "Girl Baby Shower", 
    price: 1750, 
    originalPrice: 2100, 
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500", 
    description: "Pastel colored baby shower balloon setup", 
    fullDescription: "Welcome your baby girl with our beautiful pastel-themed baby shower decoration.", 
    features: ["Soft pastel color palette", "Premium balloon garland installation", "Gender-specific themed elements", "Cute and adorable props", "Instagram-worthy photo corners", "Coordinated table decorations"], 
    includes: "Balloon arrangements, themed props, welcome signage, and complete color coordination", 
    setupTime: "2-3 hours", 
    rating: 4.8, 
    ratingCount: 56, 
    discount: 17 
  },
  { 
    id: 8, 
    name: "Baby Shower Ring Setup", 
    category: "baby-shower", 
    subCategory: "Twin Baby Shower", 
    price: 4200, 
    originalPrice: 5000, 
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?w=500", 
    description: "Premium circular baby shower decoration", 
    fullDescription: "Double the joy with our premium twin baby shower decoration package.", 
    features: ["Unique circular/ring design setup", "Dual-theme elements for twins", "Premium quality materials throughout", "360-degree decorated centerpiece", "Matching pair decorative elements", "Special twin-themed accessories"], 
    includes: "Circular structure setup, dual theme coordination, premium materials, and specialized twin-themed decor", 
    setupTime: "4 hours", 
    rating: 4.9, 
    ratingCount: 41, 
    discount: 16 
  },
  { 
    id: 9, 
    name: "Baby Shower Ring Setup Premium", 
    category: "baby-shower", 
    subCategory: "Gender Reveal", 
    price: 2300, 
    originalPrice: 2800, 
    image: "https://images.unsplash.com/photo-1607344645866-009c320b63e0?w=500", 
    description: "Yellow themed baby shower decoration ring", 
    fullDescription: "Keep everyone guessing with our exciting gender reveal party decoration.", 
    features: ["Gender-neutral yellow theme", "Question mark and surprise elements", "Reveal-ready balloon arrangements", "Photo-worthy reveal backdrop", "Anticipation-building decorations", "Includes reveal props and accessories"], 
    includes: "Complete gender reveal setup, neutral theme decor, reveal props, and photo backdrop", 
    setupTime: "3 hours", 
    rating: 4.7, 
    ratingCount: 44, 
    discount: 18 
  },

  // ===== ANNIVERSARY DECORATIONS =====
  { 
    id: 3, 
    name: "Golden 25th Anniversary Special", 
    category: "anniversary", 
    subCategory: "25th Anniversary", 
    price: 4699, 
    originalPrice: 5500, 
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=500", 
    description: "Luxurious golden themed anniversary decoration", 
    fullDescription: "Mark your 25 years of love and togetherness with our luxurious golden anniversary decoration package. This elegant setup celebrates your silver jubilee with sophistication and grandeur.", 
    features: ["Luxurious golden and ivory color scheme", "Premium metallic balloons and draping", "Elegant table settings with golden accents", "Romantic lighting arrangements", "Personalized anniversary milestone display", "Professional photography backdrop"], 
    includes: "Complete venue transformation, lighting setup, floral arrangements, personalized elements, and professional styling", 
    setupTime: "4-5 hours", 
    rating: 4.9, 
    ratingCount: 38, 
    discount: 15 
  },

  // ===== THEME DECORATIONS =====
  { 
    id: 5, 
    name: "Jungle Theme Décor Setup", 
    category: "theme", 
    subCategory: "Jungle Theme", 
    price: 2700, 
    originalPrice: 3200, 
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500", 
    description: "Wild and adventurous jungle themed decoration", 
    fullDescription: "Take your guests on a wild adventure through the jungle with our immersive themed decoration package.", 
    features: ["Life-sized animal cutouts and props", "Lush green foliage and tropical elements", "Safari-themed backdrop for photos", "Jungle-inspired table settings", "Themed entrance archway", "Animal print balloons and banners"], 
    includes: "Complete theme transformation, props, signage, tableware suggestions, and immersive decorative elements", 
    setupTime: "3-4 hours", 
    rating: 4.7, 
    ratingCount: 29, 
    discount: 16 
  },
  { 
    id: 10, 
    name: "Extravagant Beautiful Balloons", 
    category: "theme", 
    subCategory: "Princess Theme", 
    price: 3700, 
    originalPrice: 4500, 
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=500", 
    description: "Luxurious multi-color balloon decoration", 
    fullDescription: "Make your little princess feel like royalty with our extravagant princess-themed decoration package.", 
    features: ["Royal princess theme throughout", "Castle and crown decorative elements", "Luxurious balloon arrangements", "Pink and gold color scheme", "Throne photo op area", "Princess-themed props and accessories"], 
    includes: "Complete princess theme transformation, castle backdrop, crown elements, and royal-themed accessories", 
    setupTime: "4 hours", 
    rating: 4.6, 
    ratingCount: 37, 
    discount: 18 
  },
  { 
    id: 11, 
    name: "Superhero Adventure Theme", 
    category: "theme", 
    subCategory: "Superhero Theme", 
    price: 3200, 
    originalPrice: 3800, 
    image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=500", 
    description: "Action-packed superhero themed decoration", 
    fullDescription: "Transform your venue into a superhero headquarters with our action-packed themed decoration.", 
    features: ["Popular superhero characters and logos", "City skyline backdrop", "Bold primary color scheme", "Action pose photo opportunities", "Comic book style decorative elements", "Hero mask party favors"], 
    includes: "Superhero themed backdrop, character cutouts, themed balloons, and action-packed decorative elements", 
    setupTime: "3-4 hours", 
    rating: 4.8, 
    ratingCount: 52, 
    discount: 16 
  }
];

export default products;